#!/usr/bin/env node
// StuxieDev Projects — local static dev server.
//
// Serves the repo root as-is, except for one route: /assets/js/dev-mode.js
// is generated on the fly instead of read from disk, so DEV_MODE can be
// forced on for local runs without ever touching (or risking a commit of)
// the real, gitignored-free, always-`false` file in assets/js/dev-mode.js.
//
// Usage: node dev-server.js [port] [--no-dev-mode]
const http = require("http");
const fs = require("fs");
const path = require("path");

const ROOT = __dirname;
const args = process.argv.slice(2);
let port = 8080;
let devMode = true;

for (const arg of args) {
  if (arg === "--no-dev-mode") {
    devMode = false;
  } else if (/^\d+$/.test(arg)) {
    port = parseInt(arg, 10);
  } else {
    console.error(`Unknown option: ${arg}`);
    process.exit(1);
  }
}

const MIME = {
  ".html": "text/html; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".ico": "image/x-icon",
  ".json": "application/json; charset=utf-8",
  ".txt": "text/plain; charset=utf-8",
};

const server = http.createServer((req, res) => {
  const urlPath = decodeURIComponent(req.url.split("?")[0]);

  if (urlPath === "/assets/js/dev-mode.js") {
    res.writeHead(200, { "Content-Type": MIME[".js"] });
    res.end(`// Generated by dev-server.js for this run.\nwindow.DEV_MODE = ${devMode};\n`);
    return;
  }

  let filePath = path.join(ROOT, urlPath);

  // Directory / pretty-URL fallback: /legal/privacy/ -> /legal/privacy/index.html
  const tryPaths = [filePath];
  if (urlPath.endsWith("/")) {
    tryPaths.push(path.join(filePath, "index.html"));
  } else {
    tryPaths.push(path.join(filePath, "index.html"));
    tryPaths.push(`${filePath}.html`);
  }

  const found = tryPaths.find((p) => {
    try {
      return fs.statSync(p).isFile();
    } catch {
      return false;
    }
  });

  if (!found) {
    res.writeHead(404, { "Content-Type": MIME[".html"] });
    res.end("<h1>404 — Not found</h1>");
    return;
  }

  const ext = path.extname(found);
  res.writeHead(200, { "Content-Type": MIME[ext] || "application/octet-stream" });
  fs.createReadStream(found).pipe(res);
});

server.listen(port, "127.0.0.1", () => {
  console.log(`StuxieDev Projects running at http://127.0.0.1:${port}`);
  if (devMode) {
    console.log("DEV_MODE forced on for this run (banner shows) — pass --no-dev-mode to disable.");
  } else {
    console.log("DEV_MODE forced off for this run — behaving like production.");
  }
});
