#!/usr/bin/env python3
"""Regenerate sitemap.xml and sitemap/index.html for this static site.

Run from anywhere: python scripts/build-sitemap.py
The page list is PAGES below; each page's <lastmod> is the date of the last git commit that
touched its source file (left out if the file has no history yet). URLs always use BASE_URL,
the site's production address (from CNAME). The HTML page reuses the Boring Legal Stuff hub as
its layout (header, theme, footer).

Copyright (c) 2026 StuxieDev. All Rights Reserved.
"""
import html
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BASE_URL = "https://" + (ROOT / "CNAME").read_text(encoding="utf-8").strip()

# (path, source file, label, description, priority, changefreq)
PAGES = [
    ("/", "index.html", "Home", "Projects built and maintained by StuxieDev: tools, mods and utilities.", "1.0", "monthly"),
    ("/legal/", "legal/index.html", "Boring Legal Stuff", "Privacy, terms, cookies, imprint, disclaimer and opt-out preferences, all in one place.", "0.3", "yearly"),
    ("/legal/privacy/", "legal/privacy/index.html", "Privacy Policy", "What we collect (almost nothing) and why.", "0.2", "yearly"),
    ("/legal/terms/", "legal/terms/index.html", "Terms and Ethics", "The rules for using the site, and using it responsibly.", "0.2", "yearly"),
    ("/legal/cookies/", "legal/cookies/index.html", "Cookies Policy", "No tracking cookies, just one local preference, if that.", "0.2", "yearly"),
    ("/legal/imprint/", "legal/imprint/index.html", "Imprint", "Who operates this site and how to reach them.", "0.2", "yearly"),
    ("/legal/disclaimer/", "legal/disclaimer/index.html", "Disclaimer", "Copyright, accuracy, and third-party links.", "0.2", "yearly"),
    ("/legal/opt-out/", "legal/opt-out/index.html", "Opt-Out Preferences", "There's nothing to sell, so nothing to opt out of.", "0.2", "yearly"),
    ("/changelogs/", "changelogs/index.html", "Changelogs", "Release notes for this site, release by release, newest first.", "0.3", "monthly"),
    ("/sitemap/", "sitemap/index.html", "Sitemap", "Every page on this site, with a link to the XML version.", "0.1", "monthly"),
]


def lastmod(rel: str) -> str:
    return subprocess.run(["git", "log", "-1", "--format=%cs", "--", rel], cwd=ROOT,
                          capture_output=True, text=True).stdout.strip()


def build_xml() -> str:
    lines = ['<?xml version="1.0" encoding="UTF-8"?>',
             '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">']
    for loc, src, _label, _desc, priority, freq in PAGES:
        lines.append("  <url>")
        lines.append(f"    <loc>{html.escape(BASE_URL + loc)}</loc>")
        mod = lastmod(src)
        if mod:
            lines.append(f"    <lastmod>{mod}</lastmod>")
        lines.append(f"    <changefreq>{freq}</changefreq>")
        lines.append(f"    <priority>{priority}</priority>")
        lines.append("  </url>")
    lines.append("</urlset>")
    return "\n".join(lines) + "\n"


def build_html() -> str:
    """The sitemap page, in the legal hub's layout."""
    page = (ROOT / "legal" / "index.html").read_text(encoding="utf-8")
    page = page.replace("<title>Boring Legal Stuff — StuxieDev Projects</title>", "<title>Sitemap — StuxieDev Projects</title>")
    page = re.sub(r'(<meta name="description" content=")[^"]*(">)',
                  r"\g<1>Every page on StuxieDev Projects, with a link to the XML sitemap.\g<2>", page, count=1)
    page = page.replace('<span class="bc-cur">Boring Legal Stuff</span>', '<span class="bc-cur">Sitemap</span>')
    page = page.replace('<h1 class="page-title">Boring Legal Stuff</h1>', '<h1 class="page-title">Sitemap</h1>')
    page = re.sub(r'<p class="page-desc">.*?</p>',
                  '<p class="page-desc">Every page on this site. Looking for the XML version? <a href="/sitemap.xml">sitemap.xml</a></p>',
                  page, count=1, flags=re.S)
    cards = []
    for loc, _src, label, desc, _p, _f in PAGES:
        cards.append(f"""        <a href="{html.escape(loc)}" class="legal-card">
          <div>
            <div class="legal-card-desc" style="overflow-wrap: anywhere;">{html.escape(BASE_URL + loc)}</div>
            <div class="legal-card-name">{html.escape(label)}</div>
            <div class="legal-card-desc">{html.escape(desc)}</div>
          </div>
        </a>""")
    start = page.index('<div class="legal-grid">')
    end = page.index("</div>\n\n      <p", start)
    page = page[:start] + '<div class="legal-grid">\n' + "\n".join(cards) + "\n      " + page[end:]
    page = re.sub(r'\n      <p style="margin-top: 2rem;.*?</p>', "", page, count=1, flags=re.S)
    notice = "<!-- Generated by scripts/build-sitemap.py; edit the PAGES list there, then re-run it. -->\n"
    return page.replace("<body>\n", "<body>\n" + notice, 1)


def main() -> None:
    (ROOT / "sitemap").mkdir(exist_ok=True)
    (ROOT / "sitemap" / "index.html").write_text(build_html(), encoding="utf-8", newline="\n")
    (ROOT / "sitemap.xml").write_text(build_xml(), encoding="utf-8", newline="\n")
    robots = ROOT / "robots.txt"
    line = f"Sitemap: {BASE_URL}/sitemap.xml"
    text = robots.read_text(encoding="utf-8") if robots.exists() else "User-agent: *\nAllow: /\n"
    if line not in text:
        text = text.rstrip("\n") + "\n\n" + line + "\n"
    robots.write_text(text, encoding="utf-8", newline="\n")
    print(f"Wrote sitemap.xml, sitemap/index.html and robots.txt for {BASE_URL} ({len(PAGES)} pages)")


if __name__ == "__main__":
    main()
